#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string


server {
    listen 80;
    server_name your_domain.com;  poshdev.tech

    # ... other configurations ...

    error_page 404 /404.html;
    location = /404.html {
        root /path/to/your/404/page;  poshdev.tech
        internal;
    }

    # ... other configurations ...
}

