#!/usr/bin/env bash

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Bind to the server's IP address
    server_name 18.234.169.165;

    # Customize HTTP response header
    add_header X-Served-By 228560-web-01;

    # Route /airbnb-onepage/ to AirBnB_clone_v3
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    # Custom 404 error page
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}

