#!/usr/bin/env bash

# Nginx configuration for a web server.

# Default server configuration
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name 18.234.169.165;
    add_header X-Served-By 228560-web-01;

    # Proxy /airbnb-onepage/ to AirBnB_clone_v3
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    # Proxy /airbnb-dynamic/number_odd_or_even/ to AirBnB_clone_v2
    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
    }

    # Proxy /api/ to AirBnB_clone_v3
    location /api/ {
        proxy_pass http://127.0.0.1:5002/;
    }

    # Proxy other requests to /2-hbnb route of AirBnB_clone_v4
    location / {
        proxy_pass http://127.0.0.1:5003/2-hbnb;
    }

    # Serve static content for AirBnB_clone_v4
    location /static {
        alias web_dynamic/static/;
    }

    # Custom 404 error page
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}

